# Source: grafana/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: jx-observability
  labels:
    helm.sh/chart: grafana-6.4.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.4.2"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: admin-user
      key: admin-user
      property: admin-user
    - name: admin-password
      key: admin-password
      property: admin-password
    - name: ldap-toml
      key: ldap-toml
      property: ldap-toml
  template:
    metadata:
      labels:
        helm.sh/chart: grafana-6.4.8
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/version: "7.4.2"
        app.kubernetes.io/managed-by: Helm
    type: Opaque
