# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: observability
  labels:
    helm.sh/chart: grafana-6.4.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.4.2"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  plugins: grafana-piechart-panel 1.6.1,briangann-datatable-panel 1.0.3
  grafana.ini: |
    [analytics]
    check_for_updates = false
    reporting_enabled = false
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [users]
    viewers_can_edit = true
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      name: Loki
      type: loki
      uid: loki
      url: http://loki.observability:3100
      version: 1
    - access: proxy
      httpMethod: POST
      name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-server.observability
      version: 1
