# Source: prometheus/templates/pushgateway/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: prometheus
    chart: prometheus-13.4.0
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: prometheus-pushgateway
  namespace: observability
  annotations: {}
