# Source: loki/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: loki
  namespace: observability
  labels:
    app: loki
    chart: loki-2.3.0
    release: loki
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"loki","properties":null,"mandatory":true}'
spec:
  backendType: local
  data:
    - name: loki.yaml
      key: loki.yaml
      property: loki.yaml
  template:
    metadata:
      labels:
        app: loki
        chart: loki-2.3.0
        release: loki
        heritage: Helm
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"loki","properties":null,"mandatory":true}'
