apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: promtail
    mandatory: true
    properties:
    - name: promtail.yaml
      key: secret/data/promtail.yaml
      question: the promtail config
      defaultValue:
